export const descriptions = [ 
    {name:'The Sun', description: 'The Sun is the star at the center of the Solar System. It is a massive, nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core, radiating the energy from its surface mainly as visible light and infrared radiation with 10% at ultraviolet energies. It is by far the most important source of energy for life on Earth. The Sun has been an object of veneration in many cultures. It has been a central subject for astronomical research since antiquity.'},
    {name:'Mercury', description: 'Mercury is the first planet from the Sun and the smallest in the Solar System. In English, it is named after the ancient Roman god Mercurius, god of commerce and communication, and the messenger of the gods'}, 
    {name:'Venus', description: 'Venus is the second planet from the Sun. It is a terrestrial planet and is the closest in mass and size to its orbital neighbour Earth. Venus has by far the densest atmosphere of the terrestrial planets, composed mostly of carbon dioxide with a thick, global sulfuric acid cloud cover.'}, 
    {name:'Earth', description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being an ocean world, the only one in the Solar System sustaining liquid surface water. Almost all of Earth\'s water is contained in its global ocean, covering 70.8% of Earth\'s crust.'},
    {name:'Mars', description: 'Mars is the fourth planet from the Sun. The surface of Mars is orange-red because it is covered in iron(III) oxide dust, giving it the nickname "the Red Planet". Mars is among the brightest objects in Earth\'s sky, and its high-contrast albedo features have made it a common subject for telescope viewing.'},
    {name:'Jupiter', description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than 2.5 times that of all the other planets in the Solar System combined and slightly less than one-thousandth the mass of the Sun. Its diameter is eleven times that of Earth, and a tenth that of the Sun'},
    {name:'Saturn', description: 'Saturn is the sixth planet from the Sun and the second largest in the Solar System, after Jupiter. It is a gas giant, with an average radius of about nine times that of Earth. It has an eighth the average density of Earth, but is over 95 times more massive.'},
    {name:'Uranus', description: 'Uranus is the seventh planet from the Sun. It is a gaseous cyan-coloured ice giant. Most of the planet is made of water, ammonia, and methane in a supercritical phase of matter, which astronomy calls "ice" or volatiles.'},
    {name:'Neptune', description: 'Neptune is the eighth and farthest known planet from the Sun. It is the fourth-largest planet in the Solar System by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth.'},
    {name:'The Moon', description: 'The Moon (also known as Earth I or Luna) is the Earth\'s natural satellite and the 5th largest spherical moon in the Solar System. Yet, it is the largest in the Solar System in relation to its host planet, being only one-fourth smaller than Earth.'},
    {name:'Phobos', description: 'Phobos, also known as Mars I, is the larger of the two satellites belonging to the inner planet of Mars. It is one of the two satellites of Mars, the other one being Deimos. It is more than seven times more massive than Deimos, and at least three times as large. Phobos has a diameter of 22.2 km (13.8 mi) and a mass of 1.08×1016 kg.'},
    {name:'Deimos', description: 'Deimos, also known as Mars I, is the smallest, and furthest satellite in orbit, of Mars. It is one of the two Mars\'s moons, the other one being its neighboring moon, Phobos. Deimos is smaller than its neighboring moon, Phobos, but they both appear to be asteroids, thus proving they were loose asteroids in space that were pulled in by Mars\' gravitational pull.'},
    {name:'Ganymede', description: 'Ganymede, also known as Jupiter III, is the largest moon in the entire Solar System, the largest of the galilean moons, and the largest of Jupiter\'s moons. Ganymede is bigger than the planet Mercury. This moon belongs to the planet Jupiter, which is ironically the largest planet in the Solar System.'},
    {name:'Europa', description: 'Europa is the smallest of the Galilean moons, behind Io, Callisto, and Ganymede, and is one of the satellites belonging to Jupiter. This moon was found by Galileo Galilei and the less credited, Simon Marius, on January 8, 1610, the day after Ganymede, the largest of Jupiter\'s natural satellites, was discovered.[1]'},
    {name:'Callisto', description: 'Callisto is a satellite belonging to the outer planet Jupiter. It is one of the Galilean moons, a group of the largest moons in the Solar System that were discovered by Galileo Galilei. Callisto was founded by Galileo Galilei on January 7, 1610, the same day as Ganymede, also a Galilean moon, and the largest moon in the Solar System, was discovered.'},
    {name:'Io', description: 'Io is the innermost of the four Galilean moons of Jupiter, discovered in 1610 by Galileo Galilei. With a diameter of 3,643 kilometers (2,264 miles), it is slightly larger than Earth\'s Moon and is the fourth-largest moon in the Solar System. '},
    {name:'Titan', description: 'Titan, also known as Saturn VI, is a prograde moon and is the largest natural satellite of the outer planet, Saturn. Is is also the second largest moon in the Solar System, just behind Ganymede,[1] one of the Galilean moons belonging to the outer planet, Jupiter. This however is the only moon known in the Solar System to have a dense atmosphere and is even believed to have surface water,[2] the only other body to have received this classification after our own Earth.'},
    {name:'Rhea', description: 'Rhea, also known as Saturn V, is a natural satellite of the outer planet Saturn. Rhea was discovered on December 23, 1672, by the astronomer Giovanni D. Cassini. It is the ninth-largest moon.'},
    {name:'Iapetus', description: 'Iapetus, also known as Saturn II, is a natural satellite of the outer planet, Saturn. Iapetus was discovered on October 25, 1671, by the astronomer G.D. Cassini.'},
    {name:'Tethys', description: 'Tethys, also known as Saturn III, is a natural satellite of the outer planet, Saturn. It was discovered on March 21, 1684 by the astronomer G.D. Cassini.'},
    {name:'Dione', description: 'Dione, also known as Saturn III is a natural satellite of the outer planet Saturn. and is the 15th largest moon in the solar system. Dione was discovered on March 21, 1684, by the astronomer Giovanni Cassini.'},
    {name:'Enceladus', description: 'Enceladus is a natural satellite of the outer planet Saturn. It was discovered on August 28, 1789, by the astronomer William Herschel. It is the sixth largest moon of Saturn, and has a diameter of 504.2 km.'},
    {name:'Mimas', description: 'Mimas, also known as Saturn VI, is a natural satellite of the outer planet, Saturn. The moon was discovered on September 17, 1789 by the British astronomer William Herschel. Mimas is the smallest astronomical body known to be in hydrostatic equilibrium. The moon\'s presence has created one of the largest \'gaps\' in Saturn\'s ring, named the Cassini Division, due to orbital resonance destabilizing the particles\' orbit there.'},
    {name:'Titania', description: 'Titania, also known as Uranus III, is a natural satellite of the outer planet Uranus. Titania was discovered on January 11, 1787 by astronomer William Herschel. It is the eighth-largest moon, and It is the largest out of the Uranian moons.'},
    {name:'Umbriel', description: 'Umbriel, also known as Uranus II, is a natural satellite of the outer planet, Uranus. Umbriel was discovered on October 24, 1851, by the astronomer William Lassel. Umbriel is the third-largest and fourth-most massive of the Uranian moons. Umbriel is the 13th-largest moon in the Solar System and also the 14th-most massive'},
    {name:'Triton', description: 'Triton, also known as Neptune I, is the biggest natural satellite of the outer planet, Neptune. It is the seventh-largest moon in the Solar System. It has a retrograde, inclined orbit around Neptune.[1] Triton was discovered on October 10, 1846 by the astronomer William Lassell. It has a diameter of 2.7 megameters.['},
];

export function getDesc(name) {
    descriptions.forEach(desc => 
        {
        if(desc.name == name)
            currentDesc = desc;
            return currentDesc;   
        }
    );
}

export let currentDesc ;